[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "frame-ancestors 'self' https://*.provisionpicks.com https://*.framer.com https://*.framer.website"
    X-Frame-Options = "ALLOW-FROM https://*.provisionpicks.com https://*.framer.com https://*.framer.website"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]